### PR TITLE
Controller fix

### LINKED ISSUE #13: Implement fight controller

### PR DESCRIPTION
**Pull request by rtrydev**
#13

### CODE REVIEW

**Comment by TomaszSteblik** [comment]
please fix random acceleration first

**Review by Maksiolo20 — APPROVED** [review]
k

**Comment by TomaszSteblik** [comment]
can you make character collide with the box?

**Review by TomaszSteblik — CHANGES_REQUESTED** [review]
fix collider

**Review by TomaszSteblik — CHANGES_REQUESTED** [review]
Add delta time please

**Review by TomaszSteblik — APPROVED** [review]
lgtm

**Pull request merged**
